#!/bin/sh

#
# chkconfig: 3 90 99
# description: glideinwms-pilot
#
# Starts the glideinWMS Pilot
#

case $1 in
'start')
    # make $OSG_APP
    mkdir -p /mnt/app
    # make $OSG_DATA
    mkdir -p /mnt/data

    mkdir -p /mnt/glidein_pilot
    chown glidein_pilot:glidein_pilot /mnt/glidein_pilot

    echo "Starting up glideinwms-pilot"
    ulimit -n 131072
    /usr/sbin/pilot-launcher
    ;;

'stop')
    echo "Not doing anything... we don't care, since the Image will start clean next time"
    ;;

*)
    echo "Usage: glideinwms-pilot {start|stop}"
    ;;

esac
