#!/bin/sh

#
# chkconfig: 3 90 99
# description: glideinwms-pilot
#
# Starts the glideinWMS Pilot
#

case $1 in
'start')
    echo "Starting up glideinwms-pilot"
    ulimit -n 131072
    /usr/sbin/pilot-launcher
    ;;

'stop')
    echo "Not doing anything... we don't care, since the Image will start clean next time"
    ;;

*)
    echo "Usage: glideinwms-pilot {start|stop}"
    ;;

esac
